.catalog:
  name: "EEA RocketChat"
  version: "v0.1-eea"
  description: "Have your own Slack like online chat, built with Meteor."
  minimum_rancher_version: v0.51.0
  questions:
    - variable: ROCKETCHAT_ROOT_URL
      description: "This is the root URL for your rocketchat server."
      label: "Rocketchat root url"
      type: "string"
      default: http://yourhost:3000
      required: true
    - variable: HUBOT_ROCKETCHAT_ROOM
      description: "Rocketchat room where hubot will post messages."
      label: "Hubot rocketchat room"
      type: "string"
      default: GENERAL
      required: true
    - variable: HUBOT_ROCKETCHAT_USER
      description: "Hubot username"
      label: "Hubot username"
      type: "string"
      default: bot
      required: true
    - variable: HUBOT_ROCKETCHAT_PASSWORD
      description: "Hubot password"
      label: "Hubot password"
      type: "password"
      default: botpassword
      required: true
    - variable: HUBOT_BOT_NAME
      description: "Hubot bot name used inside rocketchat"
      label: "Hubot bot name"
      type: "string"
      default: Mr. RoBot
      required: true
    - variable: HUBOT_EXTERNAL_SCRIPTS
      description: "You can add more hubot scripts as you'd like here, they need to be installable by npm."
      label: "Hubot external scripts"
      type: "string"
      default: hubot-help,hubot-seen,hubot-links,hubot-diagnostics
      required: true
    - variable: HOST_LABELS
      description: "Comma separated list of host labels (e.g. key1=value1,key2=value2) to be used for scheduling the services."
      label: "Schedule this stack on hosts with following host labels"
      type: "string"
      required: true
      default: rocketchat=yes
hubot:
  scale: 1
rocketchat:
  scale: 1
mongo:
  scale: 1